### ISSUE TITLE
install instructions?

### ISSUE THREAD

**Issue by rhaynes74** [tillahoffmann/obsidian-jupyter#3] opened 2021-08-31 21:49 UTC
Good day! I was wondering if there are some install instructions available? 

update: I followed the generic instructions for installing plugins.  Seems ok, the plugin shows up inside obsidian, I specify the path for the python interpreter (I think!) but things don't work.  I just get a "Running" showing up when I press run, it never stops or returns any output. 

I have tried giving the whole path to the interpreter or just the command 

python3

At the command line I get:
python3
Python 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.sin(0.2)

so python3 is in my path.    Suggestions?

**Comment by tillahoffmann** [comment] 2021-09-01 11:20
Regarding installation, it should be available via the community plugins once https://github.com/obsidianmd/obsidian-releases/pull/463 is merged.

Regarding the plugin not working as expected, could you please use the "View" > "Toggle Developer Tools" menu item and post any error messages that are shown in the console?

**Comment by rhaynes74** [comment] 2021-09-01 12:11
Many thanks for the reply.   Thanks for reminding me of the console!!

When I click on run the console reports:

File ".obsidian/plugins/obsidian-jupyter/obsidian-jupyter.py", line 3, in <module>
 from jupyter_client import Kernel
Manager
ImportError: No module named jupyter_client

Python/jupyterlab installed via home-brew on the Mac.

Jupiter lab works fine (opens in browser and works).

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment] 2021-09-01 13:37
Just to add, if I run python3 in the terminal and do the same command it works:

python3
Python 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jupyter_client import KernelManager

This seems to work fine, no error reported.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment] 2021-09-01 14:02
Ok - I was missing some python packages!  After installing a bunch of things, I now get the following error:


created new client for doc c69caa647d36a038
main.ts:43 INFO:obsidian-jupyter:started server for document c69caa647d36a038

main.ts:43 INFO:obsidian-jupyter:received request: {"id":"a6978e3c-fc8a-4ad0-8a39-b30d9620c176","body":{"command":"execute","source":"x = 4 \ny = x+2\nprint(2*y)\npass\n"}}


main.ts:43 WARNING:traitlets:Kernelspec name python3 cannot be found!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment] 2021-09-01 14:55
And one last update - it seems to be working!  I had problems with kernels.  I guess I assumed that b/c Jupyter lab was working on its own that the plugin would work, but unfortunately not the case.

One remaining issue.  When I revert back to edit mode my font sizes are all messed up.  The Jupyter code cell is rendered in a really small font.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by tillahoffmann** [comment] 2021-09-01 20:32
Thanks for the updates; glad you could get it to work. Do you have a before and after screenshot of the font size in the editor?

**Comment by rhaynes74** [comment] 2021-09-01 21:44
Please the following attachments (and thanks for your patience!)

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by tillahoffmann** [comment] 2021-09-02 08:56
Hey, unfortunately, GitHub doesn't process attachments in emails.

**Comment by rhaynes74** [comment] 2021-09-02 11:26
<img width="1065" alt="Screen Shot 2021-09-01 at 7 13 07 PM" src="https://user-images.githubusercontent.com/1008808/131835630-191a318d-ee95-4679-8289-02aea0c01991.png">
<img width="1066" alt="Screen Shot 2021-09-01 at 7 13 29 PM" src="https://user-images.githubusercontent.com/1008808/131835651-e886984b-6177-48e3-90cb-42d926287173.png">

**Comment by tillahoffmann** [comment] 2021-09-06 10:22
Unfortunately, I can't reproduce this issue here. Which operating system/obsidian version are you using?

**Comment by rhaynes74** [comment] 2021-09-07 11:00
Hi - latest Mac OS X and latest obsidian version.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by tillahoffmann** [comment] 2021-09-07 21:34
Will close this one and track in #10 instead.

**Closed as completed by tillahoffmann** 2021-09-07 21:34 UTC
Labels: question
